# Generated by Django 5.2.6 on 2025-09-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
