# Generated by Django 5.2.6 on 2025-09-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_notice_delete_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
