# Generated by Django 5.2.6 on 2025-09-10 06:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
