# Generated by Django 5.2.6 on 2025-09-10 06:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitesettings_footer_copyright_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.TextField(blank=True, default='Mayaj. All rights reserved.', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_description',
            field=ckeditor.fields.RichTextField(blank=True, default='Step into style with our premium collection of footwear for every occasion.', null=True),
        ),
    ]
