# Generated by Django 5.2.6 on 2025-09-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_sitesettings_footer_copyright_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combooffer',
            name='short_description',
        ),
    ]
