# Generated by Django 5.2.6 on 2025-09-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_combooffer_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='icon_class',
        ),
    ]
