# Generated by Django 5.2.6 on 2025-09-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_offer_background_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormField',
        ),
    ]
