# Generated by Django 5.2.6 on 2025-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_admin_notes_order_discount_order_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
