# Generated by Django 5.2.6 on 2025-09-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_shipping_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
